resources:
- manager.yaml
- configuration.yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
images:
- name: controller
  newName: registry-1.docker.io/wzrdtales/cluster-api-provider-wxone
  newTag: v1.0.2
