apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    app.kubernetes.io/name: cluster-api-provider-wxone
    app.kubernetes.io/managed-by: kustomize
  name: controller-manager-wx-one
  namespace: system
