apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
kind: WXOneCluster
metadata:
  labels:
    app.kubernetes.io/name: cluster-api-provider-wxone
    app.kubernetes.io/managed-by: kustomize
  name: wxonecluster-sample
spec:
  credentialsSecretRef:
    name: testcluster1
  project:
    name: default
  availabilityZone: wx_dus_1
  network:
    name: wxonecluster-sample
    subnets:
      - name: wxonecluster-sample-subnet
        ipversion: IPv4
        cidr: 10.0.0.0/24
  sshKey:
    name: wxonecluster-sample
    publicKey: 'ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAACAQCXqQn/Bcrg6E6nNPTWqfguSXHifaowm2Wm9NpUrVB1/QUt7DVMXyI7d65hjQRyhrd4hK7kTaEM3NfX9Fc9LZOAYmPnzMIaULRChhbItQuT1uwN69gW6Dnz5Q4N8BRQjpMBLInhz/YoSZU9cpfTT9oKqcyryUO8LAZQJT7CWaLhxv8bsWK9HZ2H1W3NrUvmimV3qDEQMGdyVte9VryKQp5LtSczzdpGrBU1AXpw+b02vDdxmgobK7BKAVTt7Xbv0jQyT5dyBnvJJu4HTcWwi1q39AYQ2Q2VX9nGsJ43OUidXKGsiHUGzUsQVw/ZWFVJj8JJ/VBeJX/7rNDHoFNMzTwhfnrs7LxNRh5cCNv6Fj+7K0DBeVRTEd4wNDj8SKVoFiUUynKNU1dv04PTArYgLTLQJ6ASlNLGTaermmkJrsp6BWaTVvTNSZ0UXmjH0YmFEKV88gQ01/Oyt8XM46ohZoISN/0HJxqDM24762I9qJBOqUep40Oq07RMT+xXmUz3bv81iuwRFxLJj5cv+Xbpp0NL7Sr0ISgGNNpdZU3nXEMeTo+8cDmYpbJm74DCVqk9EEj0UQieNFt5x6QewGEsoHXxc+v+u5PcQdo/tCtRZSXi23JMOlvHrD7ErwOBjv/sWbXW4bI5ZyjHVSykOB6rLbsZr7t+C/XEEoTCoHgrOzR7+Q=='
    projectWide: true
