apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
kind: WXOneMachineTemplate
metadata:
  labels:
    app.kubernetes.io/name: cluster-api-provider-wxone
    app.kubernetes.io/managed-by: kustomize
  name: wxonemachinetemplate-sample
spec:
  template:
    spec:
      flavor:
        name: 'dd1.medium'
      image:
        name: ubuntu2004
