//go:build !ignore_autogenerated

/*
Copyright 2025.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by controller-gen. DO NOT EDIT.

package v1beta1

import (
	runtime "k8s.io/apimachinery/pkg/runtime"
	apiv1beta1 "sigs.k8s.io/cluster-api/api/v1beta1"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *WXOneCluster) DeepCopyInto(out *WXOneCluster) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	out.Status = in.Status
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new WXOneCluster.
func (in *WXOneCluster) DeepCopy() *WXOneCluster {
	if in == nil {
		return nil
	}
	out := new(WXOneCluster)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *WXOneCluster) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *WXOneClusterList) DeepCopyInto(out *WXOneClusterList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]WXOneCluster, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new WXOneClusterList.
func (in *WXOneClusterList) DeepCopy() *WXOneClusterList {
	if in == nil {
		return nil
	}
	out := new(WXOneClusterList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *WXOneClusterList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *WXOneClusterSpec) DeepCopyInto(out *WXOneClusterSpec) {
	*out = *in
	out.Project = in.Project
	in.Network.DeepCopyInto(&out.Network)
	out.SSHKey = in.SSHKey
	out.ControlPlaneEndpoint = in.ControlPlaneEndpoint
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new WXOneClusterSpec.
func (in *WXOneClusterSpec) DeepCopy() *WXOneClusterSpec {
	if in == nil {
		return nil
	}
	out := new(WXOneClusterSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *WXOneClusterStatus) DeepCopyInto(out *WXOneClusterStatus) {
	*out = *in
	out.Project = in.Project
	out.Network = in.Network
	out.SSHKey = in.SSHKey
	out.FloatingIP = in.FloatingIP
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new WXOneClusterStatus.
func (in *WXOneClusterStatus) DeepCopy() *WXOneClusterStatus {
	if in == nil {
		return nil
	}
	out := new(WXOneClusterStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *WXOneClusterTemplate) DeepCopyInto(out *WXOneClusterTemplate) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	out.Status = in.Status
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new WXOneClusterTemplate.
func (in *WXOneClusterTemplate) DeepCopy() *WXOneClusterTemplate {
	if in == nil {
		return nil
	}
	out := new(WXOneClusterTemplate)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *WXOneClusterTemplate) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *WXOneClusterTemplateList) DeepCopyInto(out *WXOneClusterTemplateList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]WXOneClusterTemplate, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new WXOneClusterTemplateList.
func (in *WXOneClusterTemplateList) DeepCopy() *WXOneClusterTemplateList {
	if in == nil {
		return nil
	}
	out := new(WXOneClusterTemplateList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *WXOneClusterTemplateList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *WXOneClusterTemplateResource) DeepCopyInto(out *WXOneClusterTemplateResource) {
	*out = *in
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new WXOneClusterTemplateResource.
func (in *WXOneClusterTemplateResource) DeepCopy() *WXOneClusterTemplateResource {
	if in == nil {
		return nil
	}
	out := new(WXOneClusterTemplateResource)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *WXOneClusterTemplateSpec) DeepCopyInto(out *WXOneClusterTemplateSpec) {
	*out = *in
	in.Template.DeepCopyInto(&out.Template)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new WXOneClusterTemplateSpec.
func (in *WXOneClusterTemplateSpec) DeepCopy() *WXOneClusterTemplateSpec {
	if in == nil {
		return nil
	}
	out := new(WXOneClusterTemplateSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *WXOneClusterTemplateStatus) DeepCopyInto(out *WXOneClusterTemplateStatus) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new WXOneClusterTemplateStatus.
func (in *WXOneClusterTemplateStatus) DeepCopy() *WXOneClusterTemplateStatus {
	if in == nil {
		return nil
	}
	out := new(WXOneClusterTemplateStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *WXOneFlavor) DeepCopyInto(out *WXOneFlavor) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new WXOneFlavor.
func (in *WXOneFlavor) DeepCopy() *WXOneFlavor {
	if in == nil {
		return nil
	}
	out := new(WXOneFlavor)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *WXOneFloatingIPResource) DeepCopyInto(out *WXOneFloatingIPResource) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new WXOneFloatingIPResource.
func (in *WXOneFloatingIPResource) DeepCopy() *WXOneFloatingIPResource {
	if in == nil {
		return nil
	}
	out := new(WXOneFloatingIPResource)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *WXOneImage) DeepCopyInto(out *WXOneImage) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new WXOneImage.
func (in *WXOneImage) DeepCopy() *WXOneImage {
	if in == nil {
		return nil
	}
	out := new(WXOneImage)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *WXOneMachine) DeepCopyInto(out *WXOneMachine) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new WXOneMachine.
func (in *WXOneMachine) DeepCopy() *WXOneMachine {
	if in == nil {
		return nil
	}
	out := new(WXOneMachine)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *WXOneMachine) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *WXOneMachineList) DeepCopyInto(out *WXOneMachineList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]WXOneMachine, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new WXOneMachineList.
func (in *WXOneMachineList) DeepCopy() *WXOneMachineList {
	if in == nil {
		return nil
	}
	out := new(WXOneMachineList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *WXOneMachineList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *WXOneMachineSpec) DeepCopyInto(out *WXOneMachineSpec) {
	*out = *in
	out.Flavor = in.Flavor
	out.Image = in.Image
	if in.ProviderID != nil {
		in, out := &in.ProviderID, &out.ProviderID
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new WXOneMachineSpec.
func (in *WXOneMachineSpec) DeepCopy() *WXOneMachineSpec {
	if in == nil {
		return nil
	}
	out := new(WXOneMachineSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *WXOneMachineStatus) DeepCopyInto(out *WXOneMachineStatus) {
	*out = *in
	if in.Addresses != nil {
		in, out := &in.Addresses, &out.Addresses
		*out = make([]apiv1beta1.MachineAddress, len(*in))
		copy(*out, *in)
	}
	out.Flavor = in.Flavor
	out.Image = in.Image
	out.Instance = in.Instance
	out.FloatingIPAttachement = in.FloatingIPAttachement
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new WXOneMachineStatus.
func (in *WXOneMachineStatus) DeepCopy() *WXOneMachineStatus {
	if in == nil {
		return nil
	}
	out := new(WXOneMachineStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *WXOneMachineTemplate) DeepCopyInto(out *WXOneMachineTemplate) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	out.Status = in.Status
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new WXOneMachineTemplate.
func (in *WXOneMachineTemplate) DeepCopy() *WXOneMachineTemplate {
	if in == nil {
		return nil
	}
	out := new(WXOneMachineTemplate)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *WXOneMachineTemplate) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *WXOneMachineTemplateList) DeepCopyInto(out *WXOneMachineTemplateList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]WXOneMachineTemplate, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new WXOneMachineTemplateList.
func (in *WXOneMachineTemplateList) DeepCopy() *WXOneMachineTemplateList {
	if in == nil {
		return nil
	}
	out := new(WXOneMachineTemplateList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *WXOneMachineTemplateList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *WXOneMachineTemplateResource) DeepCopyInto(out *WXOneMachineTemplateResource) {
	*out = *in
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new WXOneMachineTemplateResource.
func (in *WXOneMachineTemplateResource) DeepCopy() *WXOneMachineTemplateResource {
	if in == nil {
		return nil
	}
	out := new(WXOneMachineTemplateResource)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *WXOneMachineTemplateSpec) DeepCopyInto(out *WXOneMachineTemplateSpec) {
	*out = *in
	in.Template.DeepCopyInto(&out.Template)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new WXOneMachineTemplateSpec.
func (in *WXOneMachineTemplateSpec) DeepCopy() *WXOneMachineTemplateSpec {
	if in == nil {
		return nil
	}
	out := new(WXOneMachineTemplateSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *WXOneMachineTemplateStatus) DeepCopyInto(out *WXOneMachineTemplateStatus) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new WXOneMachineTemplateStatus.
func (in *WXOneMachineTemplateStatus) DeepCopy() *WXOneMachineTemplateStatus {
	if in == nil {
		return nil
	}
	out := new(WXOneMachineTemplateStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *WXOneNetwork) DeepCopyInto(out *WXOneNetwork) {
	*out = *in
	if in.Subnets != nil {
		in, out := &in.Subnets, &out.Subnets
		*out = make([]WXOneSubnet, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new WXOneNetwork.
func (in *WXOneNetwork) DeepCopy() *WXOneNetwork {
	if in == nil {
		return nil
	}
	out := new(WXOneNetwork)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *WXOneNetworkResource) DeepCopyInto(out *WXOneNetworkResource) {
	*out = *in
	out.SubnetReference = in.SubnetReference
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new WXOneNetworkResource.
func (in *WXOneNetworkResource) DeepCopy() *WXOneNetworkResource {
	if in == nil {
		return nil
	}
	out := new(WXOneNetworkResource)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *WXOneProject) DeepCopyInto(out *WXOneProject) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new WXOneProject.
func (in *WXOneProject) DeepCopy() *WXOneProject {
	if in == nil {
		return nil
	}
	out := new(WXOneProject)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *WXOneResourceReference) DeepCopyInto(out *WXOneResourceReference) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new WXOneResourceReference.
func (in *WXOneResourceReference) DeepCopy() *WXOneResourceReference {
	if in == nil {
		return nil
	}
	out := new(WXOneResourceReference)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *WXOneSSHKey) DeepCopyInto(out *WXOneSSHKey) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new WXOneSSHKey.
func (in *WXOneSSHKey) DeepCopy() *WXOneSSHKey {
	if in == nil {
		return nil
	}
	out := new(WXOneSSHKey)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *WXOneSubnet) DeepCopyInto(out *WXOneSubnet) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new WXOneSubnet.
func (in *WXOneSubnet) DeepCopy() *WXOneSubnet {
	if in == nil {
		return nil
	}
	out := new(WXOneSubnet)
	in.DeepCopyInto(out)
	return out
}
